### ISSUE TITLE
Как указать режим совместимости расширения?

### ISSUE THREAD

**Issue by DitriXNew** [bia-technologies/bsl-parser#1]
Так и не смог понять, пришлось добавить в макет строку:

## Реквизиты Extension

| Наименование                                 | Реквизит                                | МетодПреобразования |
| -------------------------------------------- | --------------------------------------- | ------------------- |
| ПрефиксИмен                                  | NamePrefix                              |                     |
| Назначение                                   | ConfigurationExtensionPurpose           |                     |
| **РежимСовместимостиРасширенияКонфигурации**     | **ConfigurationExtensionCompatibilityMode** |                     |

Но это не радует :)

**Comment by theshadowco** [comment]
@DitriXNew 
Спасибо за ишузы, посмотрим
